"""
Compare MicroSwim Analyzer output against synthetic ground-truth trajectories.

Expected inputs:
    1. Ground-truth CSV generated by generate_synthetic_videos.py
    2. MicroSwim Analyzer tracking CSV, e.g. triangle_lag_jitter_motion_corrected.csv

Example:
    python compare_msa_to_ground_truth.py \
        --ground-truth synthetic_validation/outputs/triangle_lag_jitter_ground_truth.csv \
        --msa-output synthetic_validation/outputs/triangle_lag_jitter_motion_corrected.csv \
        --output-dir synthetic_validation/comparison_results \
        --make-plots

The script outputs:
    - comparison_framewise.csv
    - comparison_summary.csv
    - optional trajectory/speed/error plots
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from typing import Dict, Tuple

import numpy as np
import pandas as pd

try:
    import matplotlib.pyplot as plt
except ImportError:  # plotting is optional
    plt = None


@dataclass
class ComparisonConfig:
    ground_truth_csv: str
    msa_output_csv: str
    output_dir: str
    microns_per_pixel: float = 1.0
    make_plots: bool = False
    align_translation: bool = True


def circular_angle_error_deg(a_deg: pd.Series, b_deg: pd.Series) -> pd.Series:
    """Return absolute wrapped angular error in degrees, constrained to [0, 180]."""
    diff = (a_deg - b_deg + 180.0) % 360.0 - 180.0
    return diff.abs()


def path_length(x: pd.Series, y: pd.Series) -> float:
    dx = x.diff()
    dy = y.diff()
    return float(np.sqrt(dx**2 + dy**2).sum(skipna=True))


def net_displacement(x: pd.Series, y: pd.Series) -> float:
    valid = pd.DataFrame({"x": x, "y": y}).dropna()
    if len(valid) < 2:
        return np.nan
    return float(
        np.sqrt(
            (valid["x"].iloc[-1] - valid["x"].iloc[0]) ** 2
            + (valid["y"].iloc[-1] - valid["y"].iloc[0]) ** 2
        )
    )


def meandering_index(x: pd.Series, y: pd.Series) -> float:
    total = path_length(x, y)
    net = net_displacement(x, y)
    if total <= 0 or np.isnan(total):
        return np.nan
    return float(net / total)


def add_derived_ground_truth(gt: pd.DataFrame, microns_per_pixel: float) -> pd.DataFrame:
    gt = gt.copy()

    required = [
        "frame",
        "time_s",
        "true_world_x_px",
        "true_world_y_px",
        "true_camera_x_px",
        "true_camera_y_px",
        "true_screen_x_px",
        "true_screen_y_px",
    ]
    missing = [c for c in required if c not in gt.columns]
    if missing:
        raise ValueError(f"Ground-truth CSV missing required columns: {missing}")

    gt["true_world_x_um"] = gt["true_world_x_px"] * microns_per_pixel
    gt["true_world_y_um"] = gt["true_world_y_px"] * microns_per_pixel
    gt["true_screen_x_um"] = gt["true_screen_x_px"] * microns_per_pixel
    gt["true_screen_y_um"] = gt["true_screen_y_px"] * microns_per_pixel

    gt["true_dx_um"] = gt["true_world_x_um"].diff()
    gt["true_dy_um"] = gt["true_world_y_um"].diff()
    gt["true_dt_s"] = gt["time_s"].diff()
    gt["true_step_distance_um"] = np.sqrt(gt["true_dx_um"] ** 2 + gt["true_dy_um"] ** 2)
    gt["true_speed_um_s_derived"] = gt["true_step_distance_um"] / gt["true_dt_s"]
    gt["true_heading_deg_derived"] = np.degrees(np.arctan2(gt["true_dy_um"], gt["true_dx_um"]))

    if "true_speed_um_s" not in gt.columns:
        gt["true_speed_um_s"] = gt["true_speed_um_s_derived"]

    if "true_heading_deg" not in gt.columns:
        gt["true_heading_deg"] = gt["true_heading_deg_derived"]

    return gt


def add_derived_msa(msa: pd.DataFrame, microns_per_pixel: float) -> pd.DataFrame:
    msa = msa.copy()

    required = ["frame", "time_s", "corrected_x_px", "corrected_y_px", "tracking_success"]
    missing = [c for c in required if c not in msa.columns]
    if missing:
        raise ValueError(f"MicroSwim CSV missing required columns: {missing}")

    msa["msa_corrected_x_um"] = msa["corrected_x_px"] * microns_per_pixel
    msa["msa_corrected_y_um"] = msa["corrected_y_px"] * microns_per_pixel

    if "speed_smooth_um_s" in msa.columns:
        msa["msa_speed_um_s"] = msa["speed_smooth_um_s"]
    elif "speed_um_s" in msa.columns:
        msa["msa_speed_um_s"] = msa["speed_um_s"]
    else:
        msa["msa_dx_um"] = msa["msa_corrected_x_um"].diff()
        msa["msa_dy_um"] = msa["msa_corrected_y_um"].diff()
        msa["msa_dt_s"] = msa["time_s"].diff()
        msa["msa_speed_um_s"] = (
            np.sqrt(msa["msa_dx_um"] ** 2 + msa["msa_dy_um"] ** 2) / msa["msa_dt_s"]
        )

    if "heading_rad" in msa.columns:
        msa["msa_heading_deg"] = np.degrees(msa["heading_rad"])
    else:
        msa["msa_dx_um"] = msa["msa_corrected_x_um"].diff()
        msa["msa_dy_um"] = msa["msa_corrected_y_um"].diff()
        msa["msa_heading_deg"] = np.degrees(np.arctan2(msa["msa_dy_um"], msa["msa_dx_um"]))

    return msa


def merge_data(gt: pd.DataFrame, msa: pd.DataFrame) -> pd.DataFrame:
    merged = pd.merge(
        gt,
        msa,
        on="frame",
        suffixes=("_gt", "_msa"),
        how="inner",
    )

    if merged.empty:
        raise ValueError("No overlapping frame numbers between ground truth and MicroSwim output.")

    return merged


def align_msa_to_ground_truth(df: pd.DataFrame) -> pd.DataFrame:
    """
    Remove constant translation offset between ground truth and MicroSwim coordinates.

    This is important because MicroSwim corrected coordinates and synthetic world coordinates
    may use different arbitrary origins. Validation should evaluate trajectory shape and motion,
    not absolute coordinate origin.
    """
    df = df.copy()
    valid = df[df["tracking_success"].astype(bool)].dropna(
        subset=["true_world_x_um", "true_world_y_um", "msa_corrected_x_um", "msa_corrected_y_um"]
    )

    if len(valid) < 2:
        raise ValueError("Not enough valid tracked frames for alignment.")

    x_offset = valid["msa_corrected_x_um"].iloc[0] - valid["true_world_x_um"].iloc[0]
    y_offset = valid["msa_corrected_y_um"].iloc[0] - valid["true_world_y_um"].iloc[0]

    df["msa_aligned_x_um"] = df["msa_corrected_x_um"] - x_offset
    df["msa_aligned_y_um"] = df["msa_corrected_y_um"] - y_offset
    df["alignment_x_offset_um"] = x_offset
    df["alignment_y_offset_um"] = y_offset

    return df


def compute_framewise_errors(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["position_error_x_um"] = df["msa_aligned_x_um"] - df["true_world_x_um"]
    df["position_error_y_um"] = df["msa_aligned_y_um"] - df["true_world_y_um"]
    df["position_error_um"] = np.sqrt(
        df["position_error_x_um"] ** 2 + df["position_error_y_um"] ** 2
    )

    df["speed_error_um_s"] = df["msa_speed_um_s"] - df["true_speed_um_s"]
    df["speed_abs_error_um_s"] = df["speed_error_um_s"].abs()
    df["speed_percent_error"] = 100.0 * df["speed_error_um_s"] / df["true_speed_um_s"]
    df.loc[df["true_speed_um_s"].abs() < 1e-12, "speed_percent_error"] = np.nan
    df["speed_abs_percent_error"] = df["speed_percent_error"].abs()

    df["heading_abs_error_deg"] = circular_angle_error_deg(
        df["msa_heading_deg"],
        df["true_heading_deg"],
    )

    return df


def compute_summary(df: pd.DataFrame) -> Dict[str, float]:
    valid = df[df["tracking_success"].astype(bool)].copy()
    valid = valid.dropna(subset=["true_world_x_um", "true_world_y_um", "msa_aligned_x_um", "msa_aligned_y_um"])

    if len(valid) < 3:
        raise ValueError("Not enough valid tracked frames to compute summary metrics.")

    true_path = path_length(valid["true_world_x_um"], valid["true_world_y_um"])
    msa_path = path_length(valid["msa_aligned_x_um"], valid["msa_aligned_y_um"])

    true_net = net_displacement(valid["true_world_x_um"], valid["true_world_y_um"])
    msa_net = net_displacement(valid["msa_aligned_x_um"], valid["msa_aligned_y_um"])

    true_mi = meandering_index(valid["true_world_x_um"], valid["true_world_y_um"])
    msa_mi = meandering_index(valid["msa_aligned_x_um"], valid["msa_aligned_y_um"])

    duration_s = valid["time_s_gt"].iloc[-1] - valid["time_s_gt"].iloc[0] if "time_s_gt" in valid.columns else valid["time_s"].iloc[-1] - valid["time_s"].iloc[0]

    position_rmse = float(np.sqrt(np.nanmean(valid["position_error_um"] ** 2)))
    position_mae = float(np.nanmean(valid["position_error_um"].abs()))
    position_p95 = float(np.nanpercentile(valid["position_error_um"], 95))

    speed_mae = float(np.nanmean(valid["speed_abs_error_um_s"]))
    speed_rmse = float(np.sqrt(np.nanmean(valid["speed_error_um_s"] ** 2)))
    speed_mape = float(np.nanmean(valid["speed_abs_percent_error"]))

    heading_mae = float(np.nanmean(valid["heading_abs_error_deg"]))
    heading_p95 = float(np.nanpercentile(valid["heading_abs_error_deg"], 95))

    tracking_success_rate = float(valid["tracking_success"].astype(bool).mean())

    summary = {
        "frames_compared": int(len(valid)),
        "duration_s": float(duration_s),
        "tracking_success_rate": tracking_success_rate,
        "position_rmse_um": position_rmse,
        "position_mae_um": position_mae,
        "position_p95_error_um": position_p95,
        "speed_mae_um_s": speed_mae,
        "speed_rmse_um_s": speed_rmse,
        "speed_mape_percent": speed_mape,
        "heading_mae_deg": heading_mae,
        "heading_p95_error_deg": heading_p95,
        "true_path_length_um": float(true_path),
        "msa_path_length_um": float(msa_path),
        "path_length_error_um": float(msa_path - true_path),
        "path_length_abs_percent_error": float(abs(100.0 * (msa_path - true_path) / true_path)) if true_path > 0 else np.nan,
        "true_net_displacement_um": float(true_net),
        "msa_net_displacement_um": float(msa_net),
        "net_displacement_error_um": float(msa_net - true_net),
        "net_displacement_abs_percent_error": float(abs(100.0 * (msa_net - true_net) / true_net)) if true_net > 0 else np.nan,
        "true_meandering_index": float(true_mi),
        "msa_meandering_index": float(msa_mi),
        "meandering_index_error": float(msa_mi - true_mi),
    }

    return summary


def make_plots(df: pd.DataFrame, summary: Dict[str, float], output_dir: str) -> None:
    if plt is None:
        print("matplotlib is not installed; skipping plots.")
        return

    os.makedirs(output_dir, exist_ok=True)

    valid = df[df["tracking_success"].astype(bool)].copy()

    # Trajectory comparison
    fig = plt.figure(figsize=(7, 7))
    plt.plot(valid["true_world_x_um"], valid["true_world_y_um"], label="Ground truth")
    plt.plot(valid["msa_aligned_x_um"], valid["msa_aligned_y_um"], label="MicroSwim output")
    plt.gca().set_aspect("equal", adjustable="box")
    plt.xlabel("x (um)")
    plt.ylabel("y (um)")
    plt.title("Trajectory comparison")
    plt.legend()
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "trajectory_comparison.png"), dpi=300)
    plt.close(fig)

    # Position error over time
    time_col = "time_s_gt" if "time_s_gt" in valid.columns else "time_s"
    fig = plt.figure(figsize=(9, 4))
    plt.plot(valid[time_col], valid["position_error_um"])
    plt.xlabel("Time (s)")
    plt.ylabel("Position error (um)")
    plt.title(f"Position error over time | RMSE = {summary['position_rmse_um']:.3f} um")
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "position_error_over_time.png"), dpi=300)
    plt.close(fig)

    # Speed comparison
    fig = plt.figure(figsize=(9, 4))
    plt.plot(valid[time_col], valid["true_speed_um_s"], label="Ground truth")
    plt.plot(valid[time_col], valid["msa_speed_um_s"], label="MicroSwim output")
    plt.xlabel("Time (s)")
    plt.ylabel("Speed (um/s)")
    plt.title("Speed comparison")
    plt.legend()
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "speed_comparison.png"), dpi=300)
    plt.close(fig)

    # Heading error
    fig = plt.figure(figsize=(9, 4))
    plt.plot(valid[time_col], valid["heading_abs_error_deg"])
    plt.xlabel("Time (s)")
    plt.ylabel("Heading absolute error (deg)")
    plt.title("Heading error over time")
    plt.tight_layout()
    fig.savefig(os.path.join(output_dir, "heading_error_over_time.png"), dpi=300)
    plt.close(fig)


def compare(config: ComparisonConfig) -> Tuple[pd.DataFrame, pd.DataFrame]:
    os.makedirs(config.output_dir, exist_ok=True)

    gt = pd.read_csv(config.ground_truth_csv)
    msa = pd.read_csv(config.msa_output_csv)

    gt = add_derived_ground_truth(gt, config.microns_per_pixel)
    msa = add_derived_msa(msa, config.microns_per_pixel)

    df = merge_data(gt, msa)

    if config.align_translation:
        df = align_msa_to_ground_truth(df)
    else:
        df["msa_aligned_x_um"] = df["msa_corrected_x_um"]
        df["msa_aligned_y_um"] = df["msa_corrected_y_um"]
        df["alignment_x_offset_um"] = 0.0
        df["alignment_y_offset_um"] = 0.0

    df = compute_framewise_errors(df)
    summary = compute_summary(df)
    summary_df = pd.DataFrame([summary])

    framewise_path = os.path.join(config.output_dir, "comparison_framewise.csv")
    summary_path = os.path.join(config.output_dir, "comparison_summary.csv")

    df.to_csv(framewise_path, index=False)
    summary_df.to_csv(summary_path, index=False)

    if config.make_plots:
        make_plots(df, summary, config.output_dir)

    print("\nComparison complete")
    print(f"Framewise comparison: {framewise_path}")
    print(f"Summary metrics:       {summary_path}")
    print("\nSummary:")
    print(summary_df.T.to_string(header=False))

    return df, summary_df


def parse_args() -> ComparisonConfig:
    parser = argparse.ArgumentParser(
        description="Compare MicroSwim Analyzer tracking output against synthetic ground truth."
    )
    parser.add_argument(
        "--ground-truth",
        required=True,
        help="Path to synthetic ground-truth CSV.",
    )
    parser.add_argument(
        "--msa-output",
        required=True,
        help="Path to MicroSwim Analyzer motion-corrected CSV.",
    )
    parser.add_argument(
        "--output-dir",
        default="synthetic_validation/comparison_results",
        help="Directory where comparison outputs will be saved.",
    )
    parser.add_argument(
        "--microns-per-pixel",
        type=float,
        default=1.0,
        help="Spatial calibration used during analysis.",
    )
    parser.add_argument(
        "--make-plots",
        action="store_true",
        help="Generate trajectory, speed, and error plots.",
    )
    parser.add_argument(
        "--no-align-translation",
        action="store_true",
        help="Disable constant translation alignment between MicroSwim and ground truth coordinates.",
    )

    args = parser.parse_args()

    return ComparisonConfig(
        ground_truth_csv=args.ground_truth,
        msa_output_csv=args.msa_output,
        output_dir=args.output_dir,
        microns_per_pixel=args.microns_per_pixel,
        make_plots=args.make_plots,
        align_translation=not args.no_align_translation,
    )


def main() -> None:
    config = parse_args()
    compare(config)


if __name__ == "__main__":
    main()
